# SPDX-FileCopyrightText: 2020-2023 CERN
# SPDX-FileCopyrightText: 2023 GSI Helmholtzzentrum für Schwerionenforschung
# SPDX-FileNotice: All rights not expressly granted are reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later OR EUPL-1.2+

include:
  - project: acc-co/devops/python/acc-py-gitlab-ci-templates
    file: v2/python.gitlab-ci.yml

variables:
  PY_VERSION: "3.7"
  ACC_PY_BASE_IMAGE_TAG: '2020.11'
  project_name: cernml.extremum_seeking

build_wheel:
  extends: .acc_py_build_wheel

test_pre-commit:
  extends: .acc_py_pre-commit
  variables:
    PY_VERSION: "3.9"
  before_script:
    - !reference [.acc_py_pre-commit, before_script]
    - python -m pip install pylint mypy .[lint]

test_dev:
  extends:
    - .acc_py_dev_test
    - .acc_py_run_on_all_currently_supported
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  # Override `script` to change the precise pytest-cov arguments.
  script:
    - cd ${project_root}
    - python -m pytest
      --cov=src
      --cov-branch
      --cov-report=term
      --cov-report=html:coverage-html
      --cov-report=xml:coverage-report.xml
      --junitxml=junit-report.xml

test_wheel:
  extends:
    - .acc_py_wheel_test
    - .acc_py_run_on_all_currently_supported
  variables:
    PYTEST_ADDOPTS: "-c ${CI_PROJECT_DIR}/pyproject.toml"

build_docs:
  extends:
    - .acc_py_build_docs
  variables:
    PY_VERSION: "3.9"
    SPHINX_BUILD_ADDOPTS: "-n -W" # nitpicky mode, warnings are errors
  before_script:
    - python -m pip install anybadge
    - !reference [.acc_py_build_docs, before_script]
  script:
    - !reference [.acc_py_build_docs, script]
    - sphinx_version="$(pip list | grep '^Sphinx\b' | awk '{print $2}')"
    - mkdir -p badges
    - anybadge
      --overwrite
      --label Documentation
      --value "Sphinx ${sphinx_version}"
      --color teal
      --file badges/docs.svg
  artifacts:
    paths:
      - docs/html
      - badges

publish:
  extends: .acc_py_publish

build_docs_on_tag:
  extends:
    - .acc_py_build_docs_on_tag
  variables:
    PY_VERSION: "3.9" # required for inspect.getmembers_static
    SPHINX_BUILD_ADDOPTS: "-n -W" # nitpicky mode, warnings are errors
  before_script:
    - yum -y install graphviz curl
    - !reference [.acc_py_build_docs_on_tag, before_script]

gitlab_release:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    name: 'Release $CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
