[build-system]
requires = [
    'setuptools >= 42',
    'setuptools-scm[toml] >= 6.2',
    'wheel',
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]

[tool.black]
target-version = ['py37', 'py38']
include = '\.pyi?$'

[tool.isort]
profile = 'black'

[tool.pylint.REPORTS]
output-format = 'parseable'
reports = false
score = false

[tool.pylint.'MESSAGES CONTROL']
disable = [
    'duplicate-code',
]

[tool.pytest.ini_options]
addopts = "--doctest-modules"
